### ISSUE TITLE
Failure to decompress the archive

### ISSUE THREAD

**Issue by adintya** [LionyxML/freebsd-terminus#1]
Hey Rahul,

I am trying to decompress this archive with 'xz -d vt-font-terminus-4.47.txz' and am getting this: "File format not recognized".

(I run FreeBSD 13 and my xz is of version 5.2.5)

**Comment by LionyxML** [comment]
Hey there!
Thanks for the reply.
I just decompressed it with no problems. 

Let's try some stuff:

1.) Use "file vt-font-terminus-4.47.txz" to be sure you downloaded the file and not some redirectional html.

2.) Try to do it directly via tar, as in: "tar xvfZ vt-font-terminus-4.47.txz"

3.) Try this way: "xzcat vt-font-terminus-4.47.txz | tar xvf -"


I am currently not on a FreeBSD system, but I am using:

$ xz --version
xz (XZ Utils) 5.2.5
liblzma 5.2.5

$ tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6

**Comment by adintya** [comment]
Thanks a lot, Rahul
I downloaded it anew, tried to decompress it first the old way and it worked. 

Using this opportunity, I would like to thank you for such a neat archive of terminus .fnt fonts, which is nowhere else to find!

**Comment by LionyxML** [comment]
Please spread the word. I am here to help.
Thanks!
